services:
  db_test:
    image: postgres
    container_name: db_test
    restart: always
    ports:
      - 4437:5432
    env_file:
      - back-end/.env.test
    volumes:
      - pg:/var/lib/postgresql/data

  node_app:
    container_name: node_app
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - db_test
    env_file:
      - back-end/.env.test

  react_app:
    container_name: react_app
    build: ./front-end
    volumes:
      - build_react:/var/www/html

  nginx_app:
    container_name: nginx_app
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - db_test
      - node_app
      - react_app

volumes:
  pg:
  build_react:
